version: '3.9'

services:
  api:
    image: tnosc.otriples.server.api
    container_name: apiservice
    build:
      context: .
      dockerfile: src/Tnosc.OtripleS.Server.Api/Dockerfile
    depends_on:
      - sqlserver
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=OtripleSDb;User=sa;Password=Your_Strong_Password123!;TrustServerCertificate=True;MultipleActiveResultSets=true
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire-dashboard:18889
    networks:
      - tnosc_network

networks:
  tnosc_network:
    driver: bridge