version: '3.9'

services:
  aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:latest
    container_name: aspire-dashboard
    ports:
      - "18888:18888"
      - "4317:18889"
    restart: unless-stopped

  sqlserver:
      image: mcr.microsoft.com/mssql/server:2025-latest
      container_name: sqlserver
      environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=Your_Strong_Password123!
      ports:
        - "1433:1433"
      volumes:
        - sql_data:/var/opt/mssql

volumes:
  sql_data: