// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:Tnosc.OtripleS.Server.Tests.Unit.Services.Foundations.Students.StudentServiceTests")]
[assembly: SuppressMessage("Usage", "CA2201:Do not raise reserved exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Tnosc.OtripleS.Server.Tests.Unit.Services.Foundations.Students.StudentServiceTests.ShouldThrowServiceExceptionOnRegisterIfExceptionOccursAndLogItAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "CA2201:Do not raise reserved exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Tnosc.OtripleS.Server.Tests.Unit.Services.Foundations.Students.StudentServiceTests.ShouldThrowServiceExceptionOnModifyIfExceptionOccursAndLogItAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "CA2201:Do not raise reserved exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Tnosc.OtripleS.Server.Tests.Unit.Services.Foundations.Students.StudentServiceTests.ShouldThrowServiceExceptionOnRemoveStudentByIdIfExceptionOccursAndLogItAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "CA2201:Do not raise reserved exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Tnosc.OtripleS.Server.Tests.Unit.Services.Foundations.Students.StudentServiceTests.ShouldThrowServiceExceptionOnRetrieveStudentByIdIfExceptionOccursAndLogItAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "CA2201:Do not raise reserved exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Tnosc.OtripleS.Server.Tests.Unit.Services.Foundations.Students.StudentServiceTests.ShouldThrowServiceExceptionOnRetrieveAllStudentsIfExceptionOccursAndLogItAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:Tnosc.OtripleS.Server.Tests.Unit.Services.Processings.Students.StudentProcessingServiceTests")]
[assembly: SuppressMessage("Usage", "xUnit1037:There are fewer theory data type arguments than required by the parameters of the test method", Justification = "<Pending>", Scope = "member", Target = "~M:Tnosc.OtripleS.Server.Tests.Unit.Services.Processings.Students.StudentProcessingServiceTests.ShouldThrowDependencyValidationOnUpsertIfDependencyValidationErrorOccursAndLogItAsync(Xeptions.Xeption)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "xUnit1037:There are fewer theory data type arguments than required by the parameters of the test method", Justification = "<Pending>", Scope = "member", Target = "~M:Tnosc.OtripleS.Server.Tests.Unit.Services.Foundations.Students.StudentServiceTests.ShouldThrowValidationExceptionOnModifyIfStudentUpdatedDateIsNotRecentAndLogItAsync(System.Int32)~System.Threading.Tasks.Task")]
