// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:Tnosc.OtripleS.Server.Tests.Unit.Services.Foundations.Students.StudentServiceTests")]
[assembly: SuppressMessage("Usage", "CA2201:Do not raise reserved exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Tnosc.OtripleS.Server.Tests.Unit.Services.Foundations.Students.StudentServiceTests.ShouldThrowServiceExceptionOnRegisterIfExceptionOccursAndLogItAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "CA2201:Do not raise reserved exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Tnosc.OtripleS.Server.Tests.Unit.Services.Foundations.Students.StudentServiceTests.ShouldThrowServiceExceptionOnModifyIfExceptionOccursAndLogItAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "CA2201:Do not raise reserved exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Tnosc.OtripleS.Server.Tests.Unit.Services.Foundations.Students.StudentServiceTests.ShouldThrowServiceExceptionOnRemoveStudentByIdIfExceptionOccursAndLogItAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "CA2201:Do not raise reserved exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Tnosc.OtripleS.Server.Tests.Unit.Services.Foundations.Students.StudentServiceTests.ShouldThrowServiceExceptionOnRetrieveStudentByIdIfExceptionOccursAndLogItAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "CA2201:Do not raise reserved exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Tnosc.OtripleS.Server.Tests.Unit.Services.Foundations.Students.StudentServiceTests.ShouldThrowServiceExceptionOnRetrieveAllStudentsIfExceptionOccursAndLogItAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "<Pending>", Scope = "type", Target = "~T:Tnosc.OtripleS.Server.Tests.Unit.Services.Processings.Students.StudentProcessingServiceTests")]
[assembly: SuppressMessage("Usage", "xUnit1037:There are fewer theory data type arguments than required by the parameters of the test method", Justification = "<Pending>", Scope = "member", Target = "~M:Tnosc.OtripleS.Server.Tests.Unit.Services.Processings.Students.StudentProcessingServiceTests.ShouldThrowDependencyValidationOnUpsertIfDependencyValidationErrorOccursAndLogItAsync(Xeptions.Xeption)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "xUnit1037:There are fewer theory data type arguments than required by the parameters of the test method", Justification = "<Pending>", Scope = "member", Target = "~M:Tnosc.OtripleS.Server.Tests.Unit.Services.Foundations.Students.StudentServiceTests.ShouldThrowValidationExceptionOnModifyIfStudentUpdatedDateIsNotRecentAndLogItAsync(System.Int32)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "xUnit1037:There are fewer theory data type arguments than required by the parameters of the test method", Justification = "<Pending>", Scope = "member", Target = "~M:Tnosc.OtripleS.Server.Tests.Unit.Services.Processings.Students.StudentProcessingServiceTests.ShouldThrowDependencyValidationExceptionOnUpsertIfDependencyValidationErrorOccursAndLogItAsync(Xeptions.Xeption)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "xUnit1037:There are fewer theory data type arguments than required by the parameters of the test method", Justification = "<Pending>", Scope = "member", Target = "~M:Tnosc.OtripleS.Server.Tests.Unit.Services.Processings.Students.StudentProcessingServiceTests.ShouldThrowDependencyExceptionOnUpsertIfDependencyErrorOccursAndLogItAsync(Xeptions.Xeption)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Minor Code Smell", "S1481:Unused local variables should be removed", Justification = "<Pending>", Scope = "member", Target = "~M:Tnosc.OtripleS.Server.Tests.Unit.Services.Processings.Students.StudentProcessingServiceTests.ShouldThrowServiceExceptionOnUpsertIfServiceErrorOccursAndLogItAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "CA2201:Do not raise reserved exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Tnosc.OtripleS.Server.Tests.Unit.Services.Processings.Students.StudentProcessingServiceTests.ShouldThrowServiceExceptionOnUpsertIfServiceErrorOccursAndLogItAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Performance", "CA1859:Use concrete types when possible for improved performance", Justification = "<Pending>", Scope = "member", Target = "~F:Tnosc.OtripleS.Server.Tests.Unit.Controllers.Students.StudentsControllerTests._studentService")]
[assembly: SuppressMessage("Critical Code Smell", "S6967:ModelState.IsValid should be called in controller actions", Justification = "<Pending>", Scope = "member", Target = "~M:Tnosc.OtripleS.Server.Tests.Unit.Controllers.Students.StudentsControllerTests.ShouldReturnBadRequestOnPostIfValidationErrorOccurredAsync(Xeptions.Xeption)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Critical Code Smell", "S6967:ModelState.IsValid should be called in controller actions", Justification = "<Pending>", Scope = "member", Target = "~M:Tnosc.OtripleS.Server.Tests.Unit.Controllers.Students.StudentsControllerTests.ShouldReturnInternalServerErrorOnPostIfServerErrorOccurredAsync(Xeptions.Xeption)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "CA2201:Do not raise reserved exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Tnosc.OtripleS.Server.Tests.Unit.Controllers.Students.StudentsControllerTests.ShouldReturnConflictOnPostIfAlreadyExistsStudentErrorOccurredAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Critical Code Smell", "S6967:ModelState.IsValid should be called in controller actions", Justification = "<Pending>", Scope = "member", Target = "~M:Tnosc.OtripleS.Server.Tests.Unit.Controllers.Students.StudentsControllerTests.ShouldReturnBadRequestOnPutIfValidationErrorOccurredAsync(Xeptions.Xeption)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Critical Code Smell", "S6967:ModelState.IsValid should be called in controller actions", Justification = "<Pending>", Scope = "member", Target = "~M:Tnosc.OtripleS.Server.Tests.Unit.Controllers.Students.StudentsControllerTests.ShouldReturnInternalServerErrorOnPutIfServerErrorOccurredAsync(Xeptions.Xeption)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "CA2201:Do not raise reserved exception types", Justification = "<Pending>", Scope = "member", Target = "~M:Tnosc.OtripleS.Server.Tests.Unit.Controllers.Students.StudentsControllerTests.ShouldReturnConflictOnPutIfLockedStudentErrorOccurredAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Critical Code Smell", "S6967:ModelState.IsValid should be called in controller actions", Justification = "<Pending>", Scope = "member", Target = "~M:Tnosc.OtripleS.Server.Tests.Unit.Controllers.Students.StudentsControllerTests.ShouldReturnBadRequestOnDeleteIfValidationErrorOccurredAsync(Xeptions.Xeption)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Critical Code Smell", "S6967:ModelState.IsValid should be called in controller actions", Justification = "<Pending>", Scope = "member", Target = "~M:Tnosc.OtripleS.Server.Tests.Unit.Controllers.Students.StudentsControllerTests.ShouldReturnInternalServerErrorOnDeleteIfServerErrorOccurredAsync(Xeptions.Xeption)~System.Threading.Tasks.Task")]
